### ISSUE TITLE
The cmdlet `Update-SecretStorePassword` should be `Set-SecretStorePassword` or `Edit-SecretStorePassword`

### ISSUE THREAD

**Issue by alexbuzzbee** [PowerShell/SecretStore#14]
`Update-SecretStorePassword` changes the password for a vault. However, the [Approved Verbs List](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7) defines the `Update` verb as:

> Brings a resource up-to-date to maintain its state, accuracy, conformance, or compliance. For example, the `Update-FormatData` cmdlet updates and adds formatting files to the current PowerShell console.

Its API documentation defines it as:

> Update a resource with new elements or refresh from a source of truth

That does not seem to be what `Update-SecretStorePassword` does. The most obvious correct verb to use for this is `Set`, which the Approved Verbs List defines as:

> Replaces data on an existing resource or creates a resource that contains some data. For example, the `Set-Date` cmdlet changes the system time on the local computer. (The `New` verb can also be used to create a resource.) This verb is paired with `Get`.

If `Set` seems inappropriate, the other major alternative is `Edit`, which the Approved Verbs List defines as:

> Modifies existing data by adding or removing content.

Its API documentation defines it as:

> Performs an in-place modification of a resource.

The Approved Verbs List also notes about `Edit`:

> For this action, do not use verbs such as Change, **Update**, or Modify.

(Emphasis mine.)

As this is a very new preview module, there should not be support requirements preventing this change. If there are, an alias could be used to prevent breakage.

**Comment by PaulHigin** [comment]
Thanks.  This is a good point.

**Comment by PaulHigin** [comment]
Changed in preview2.
