### ISSUE TITLE
Set-SecretStoreConfiguration without parameters prompts for confirmation

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/SecretStore#15]
Running `Set-SecretStoreConfiguration` without any changes prompts for confirmation. Are any changes being made in this example? If no changes are made I don't think there is a reason to prompt or even get this far, maybe throwing an error if no parameters were passed.

```powershell
PS C:\> Set-SecretStoreConfiguration

Confirm
Are you sure you want to perform this action?
Performing the operation "Changes local store configuration" on target "SecretStore module local store".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

**Comment by PaulHigin** [comment]
Thanks yes, this is a bug.  Will fix.

**Comment by PaulHigin** [comment]
Fixed preview2.
