### ISSUE TITLE
Unlock-SecretStore Password parameter string type

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/SecretStore#17]
Why does this cmdlet have a `-Password` parameter with the type of `[string]`? It goes against the `AvoidUsingPlainTextForPassword` PSScriptAnalyzer rule. I'd rather have users use `Read-Host -AsSecureString` or `ConvertTo-SecureString` cmdlets to generate a secure string first to use the the secure store cmdlets.

https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/AvoidUsingPlainTextForPassword.md

**Comment by PaulHigin** [comment]
We debated about whether to include it, as you point out it is not good practice, but eventually decided to.  We can always remove it.  Also note that by default the cmdlet always prompts for secure string.

**Comment by SydneyhSmith** [comment]
Thanks for the input, would love to leave this open for more community input

**Comment by PaulHigin** [comment]
I'm convinced.  I'll remove it for the next preview release.  We can always add it back in if someone makes a compelling reason.  But I can't think of a scenario right now where plain text password parameter is a good idea.

**Comment by PaulHigin** [comment]
Fixed for preview2
