### ISSUE TITLE
Support pipelining

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretStore#19]
For example:

```pwsh
Get-Secret -Name foo -Vault OtherVault  | Set-Secret -Vault SecretStore
```

Should be just a matter of adding the pipeline options to the parameter attribute.

**Comment by PaulHigin** [comment]
Good point.  I agree this should be supported.

**Comment by SydneyhSmith** [comment]
Closing this as a duplicate of https://github.com/PowerShell/SecretManagement/issues/36
