### ISSUE TITLE
Allow data file to be stored in an alternative location.

### ISSUE THREAD

**Issue by christofjans** [PowerShell/SecretStore#21]
According to the design docs, the data file is always stored in `$env:USERPROFILE\AppData\Local\Microsoft\PowerShell\secretmanagement\localstore\` .

I would like the data file to be synced across multiple devices with something like OneDrive or Google Drive (I'm comfortable with the security/convenience tradeoffs of this when using password encryption).

This would require the data file to be stored in a location different from the default.

**update** : actually, after having read more about the design of the data file, I'm not sure this would work at all. Feel free to close this issue.

**Comment by PaulHigin** [comment]
For security reasons, I think we want to keep secrets data on the local machine.  Vault extensions (based on Az KeyVault, AWS KMS, ...) is the mechanism to store/retrieve from other locations.  I'll close this for now but I am open if a good use case can be shown.
