### ISSUE TITLE
ProjectUri entry is missing from src/Microsoft.PowerShell.SecretStore.psd1

### ISSUE THREAD

**Issue by mklement0** [PowerShell/SecretStore#23]
The `PrivateData.PSData.ProjectUri` entry in the module manifest is what tells the PowerShell Gallery where a module's repository can be found, and is surfaced via a `Project Site` link in the sidebar on the left:

![image](https://user-images.githubusercontent.com/588825/94089756-f2ba8380-fde1-11ea-8bcf-2c8ea47a0750.png)

This entry is currently missing from the manifest (the repo is currently only linked to from the `Description` key, and that part isn't visible by default).

**Comment by SydneyhSmith** [comment]
Thanks @mklement0 we will update this for the next release (preview 2)

**Comment by PaulHigin** [comment]
Fixed in preview2.
