### ISSUE TITLE
Set-SecretStoreConfiguration -PassThru Parameter

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/SecretStore#25]
Currently `Set-SecretStoreConfiguration` outputs a `Microsoft.PowerShell.SecretStore.SecureStoreConfig` object by default. It may be better to not output unless a `-PassThru` parameter is passed like other `Set-*` cmdlets, for example `Set-Service`. That removes the need for users to pipe to `Out-Null` or assign it to `$null` or cast to `[void]` to suppress the output.

```powershell
PS C:\> Set-SecretStoreConfiguration -PasswordTimeout 500

Confirm
Are you sure you want to perform this action?
Performing the operation "Changes local store configuration" on target "SecretStore module local store".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
Vault Microsoft.PowerShell.SecretStore requires a password.
Enter password:
****

      Scope PasswordRequired PasswordTimeout DoNotPrompt
      ----- ---------------- --------------- -----------
CurrentUser             True             500       False
```

**Comment by PaulHigin** [comment]
I personally like have the confirmation, but I agree that this would be more consistent with other cmdlets.

**Comment by PaulHigin** [comment]
Implemented for preview3.
