### ISSUE TITLE
Set-SecretStorePassword -Password and -NewPassword Parameters

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/SecretStore#26]
To support non-interactive scenarios where automation needs to change the secrete store passwords a `-Passsword` and `-NewPassword` parameters of type `[SecureString]` can be added.

**Comment by PaulHigin** [comment]
Agreed.  This would be important when rolling over passwords.

**Comment by PaulHigin** [comment]
Implemented for preview3.
