### ISSUE TITLE
Set-Secret and Get-SecretStoreConfiguration throws an exception as a normal user

### ISSUE THREAD

**Issue by swinster** [PowerShell/SecretStore#28]
Installed both `SecretManagement` and `SecretStore` from an elevated prompt. Then registered two `SecretStore` vaults, one under and Administrator scope via the elevated prompt, and one as a normal user scope. When attempting to `Set-Secret` as the normal user, the exception is : 

```
PS C:\Users\Me> Set-Secret -Name MySecret Secret "TestSecret"
Exception calling "GetInstance" with "0" argument(s): "The type initializer for
'Microsoft.PowerShell.SecretStore.SecureStoreFile' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerShell.SecretStore\0.5.2\Microsoft.PowerShell.SecretStore.E
xtension\Microsoft.PowerShell.SecretStore.Extension.psm1:123 char:17
+ ...         if ([Microsoft.PowerShell.SecretStore.LocalSecretStore]::GetI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TypeInitializationException

Exception calling "GetInstance" with "0" argument(s): "The type initializer for
'Microsoft.PowerShell.SecretStore.SecureStoreFile' threw an exception."
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerShell.SecretStore\0.5.2\Microsoft.PowerShell.SecretStore.E
xtension\Microsoft.PowerShell.SecretStore.Extension.psm1:123 char:17
+ ...         if ([Microsoft.PowerShell.SecretStore.LocalSecretStore]::GetI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TypeInitializationException
```

Even running `Get-SecretStoreConfiguration` under the normal user scope results in: 

```
PS C:\Users\Me> Get-SecretStoreConfiguration
Get-SecretStoreConfiguration : The type initializer for 'Microsoft.PowerShell.SecretStore.SecureStoreFile' threw an
exception.
At line:1 char:1
+ Get-SecretStoreConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SecretStoreConfiguration], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.SecretStore.GetSecretStoreConfig
   uration
```

**Comment by swinster** [comment]
Looks like rebooting might have resolved this

**Comment by PaulHigin** [comment]
I am not clear on the repro steps.  Did you install the modules and vaults under two accounts, one admin and one not?  I have tested this without any problems.  The type initializer exception suggests you have two different versions of SecretStore or SecretManagement.  During preview, each version is incompatible with the other.  So be sure and uninstall the old versions before you install the new.

**Comment by swinster** [comment]
Hey @PaulHigin. Installation of the modules were under a single users account, but from an elevated PS window, then re-run under the normal user context. No previous modules were install, only the last releases of SecretStore or SecretManagement. TBH, I managed to get something similar to happen on two other machines as well.

**Comment by PaulHigin** [comment]
@swinster One other thing that may result in type initializer error is if you installed onto a Windows machine without netstandard2.0.  PowerShell 7+ will include the needed binaries, but if you are running WindowsPowerShell, the netstandard binaries will not be there by default.  Installing PowerShell 7+ will include them or you can get it from netstandard.library package from nuget.org.

**Comment by swinster** [comment]
Was using the latest version of PS7....

**Comment by PaulHigin** [comment]
I am changing how the module binaries are built, targeting net461 framework rather than netstandard2.0.  This should improve compatibility with PS7 and PS5.1.  This may solve your issue since the exception above is thrown during store file creation, and may be related to the access control API compatibility issue my change addresses.

**Comment by PaulHigin** [comment]
Implemented in preview4 changes.
