### ISSUE TITLE
Cannot Save-Module Microsoft.PowerShell.SecretStore -AllowPrerelease

### ISSUE THREAD

**Issue by crlogic** [PowerShell/SecretStore#39]
Offline systems need modules moved to them manually.

This works --> Save-Module Microsoft.PowerShell.SecretManagement -AllowPrerelease -Path $savefolder   

This doesn't --> Save-Module Microsoft.PowerShell.SecretStore -AllowPrerelease -Path $savefolder

OS: Windows 10
PWSH v7.0.3

Save-Module Microsoft.PowerShell.SecretStore -AllowPrerelease -Path C:\Users\user\tmp
WARNING: Unable to find dependent module(s) (Microsoft.PowerShell.SecretManagement)
WARNING: Package 'Microsoft.PowerShell.SecretStore' failed to install.
Save-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:11792:21
 Line |
11792 |              $null = PackageManagement\Save-Package @PSBoundParameters
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Unable to save the module 'Microsoft.PowerShell.SecretStore'.

**Comment by PaulHigin** [comment]
This is not a SecretStore issue, but a problem with PowerShellGet V2 for modules with dependencies and preview versions.  I believe it will be addressed in PowerShellGet V3.
