### ISSUE TITLE
Windows 11 Upgrade: Store File Corruption 

### ISSUE THREAD

**Issue by JackDDavis** [PowerShell/SecretStore#83]
SecretStore files corrupted after Windows 11 upgrade.

Error:
MethodInvocationException: Exception calling "PromptAndUnlockVault" with "2" argument(s): "Store file integrity check failed. The provided
password may be invalid, or store files have become corrupted or have been tampered with."

**Comment by PaulHigin** [comment]
Thanks for reporting this.  I believe this has been fixed with: https://github.com/PowerShell/SecretStore/pull/81, and is part of the 1.03 release:

https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretStore/1.0.3
